EXTENSION = tsvector_concat_raw
MODULE_big = tsvector_concat_raw
DATA = tsvector_concat_raw--0.0.1.sql
OBJS = tsvector_concat_raw.o
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
