EXTENSION = tsvector_num_lexemes
MODULE_big = tsvector_num_lexemes
DATA = tsvector_num_lexemes--0.0.1.sql
OBJS = tsvector_num_lexemes.o
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
