EXTENSION = tsvector_num_lexemes
MODULE_big = tsvector_num_lexemes
DATA = tsvector_num_lexemes--1.0.sql
DOCS = README.tsvector_num_lexemes
OBJS = tsvector_num_lexemes.o

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
