EXTENSION = tsvector_max_position
MODULE_big = tsvector_max_position
DATA = tsvector_max_position--0.0.1.sql
OBJS = tsvector_max_position.o
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
