EXTENSION = tsvector_add_offset
MODULE_big = tsvector_add_offset
DATA = tsvector_add_offset--0.0.1.sql
OBJS = tsvector_add_offset.o
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
